IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Tag')
BEGIN
	
	CREATE TABLE [Tag](
		[Id]						UNIQUEIDENTIFIER			PRIMARY KEY				DEFAULT NEWID(),
		[Name]						NVARCHAR(50)				NOT NULL,
		[Description]				NVARCHAR(250),
		[IsDeleted]					BIT							NOT NULL,
	);

END

