IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order')
BEGIN
	
	CREATE TABLE [Order] (
		[Id]						UNIQUEIDENTIFIER			PRIMARY KEY			DEFAULT NEWID(),
		[UserId]					UNIQUEIDENTIFIER,
		[TimeCreate]				DATETIME					NOT NULL			DEFAULT GETDATE(),
		[FullName]					NVARCHAR(250),
		[OrderStatus]				INT							NOT NULL,
		[PaymentMethodId]			UNIQUEIDENTIFIER			NOT NULL,
		[TotalPrice]				FLOAT						NOT NULL,
		[Address]					NVARCHAR(MAX)				NOT NULL,
	);

	ALTER TABLE [Order]
	ADD CONSTRAINT FK_Oder_Refer_PaymentMethod FOREIGN KEY (PaymentMethodID) REFERENCES PaymentMethod(Id);

	ALTER TABLE [Order]
	ADD CONSTRAINT FK_Order_Refer_User FOREIGN KEY (UserId) REFERENCES [User](Id);

END